### ISSUE TITLE
Need a README for morning setup checklist

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-workshop#10]
Need a place to remind facilitators what needs to be done in the morning.
- make sure everyone does a git pull

**Comment by stargaser** [comment]
* Make sure everyone has the wireless password
* Test the HDMI cable because we had a bad one as AAS231
* Hand out the pink and red sticky notes
* At AAS231, it was good to have the table at the back where the facilitators could hang out and see everyone, so perhaps set up table at the back as an item?

**Comment by sosey** [comment]
yah, we've done that every year and it's helped. My experience the last 4 years has been that about half the people haven't installed anything until they get to the workshop. 

also make sure there's a large board/pad somewhere you can write the basic web urls on for people to reference

**Comment by sosey** [comment]
dont forget to put copies of the notebooks and data they use on the sticks as well..

**Comment by JuanCab** [comment]
> dont forget to put copies of the notebooks and data they use on the sticks as well..

I guess especially if they don't have git installed on their computers.

**Comment by sosey** [comment]
yah, many wont and will just do the tarball download from github...but in case the connections are slow anyways, it's good to have the teaching notebooks and data available too, though there isn't too much big stuff this time, but getting anything pulled from astroquery might be a good idea

**Comment by JuanCab** [comment]
I can fit installers (32-bit and 64-bit for windows and linux and 64-bit for mac) as well as the tarball on a 4GB USB drives.  I'll see how many spare USB drives I have floating around, but if people could bring a few that would likely help, we can clone them the night before.

**Comment by sosey** [comment]
@eteq see if pontappidon still has a box full of usbs....

**Comment by JuanCab** [comment]
I've made up 5 USB pen drives, but only one is USB 3.0. :(  So anyone with a few USB 3.0 drives who brings them will save people grief...

**Comment by kelle** [comment]
@eblur made a Setup.md in #47. I merged it for the moment but want to keep this issue open so we have a place we can throw down notes and to remind me to do a more thorough update to that file.

**Comment by kelle** [comment]
also need a README for facilitators and philosophy of the workshop.

**Comment by pllim** [comment]
It is a little tedious now to read through all the notes here. And I see that most of them are in the `SETUP.md` file. I am going to open a PR to address the rest of the things here and then I propose we close this out.
