### ISSUE TITLE
Copy-edit workshop materials?

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-workshop#109]
@lglattly is available this week to copy-edit the notebooks: do we want to set her loose on the content?

cc @stargaser @kelle 

:heavy_check_mark:  = Ready for copyediting
:question: = Ask the instructor first
:x: = Not ready

List of notebooks as of AAS 235:

- [x] `03-UnitsQuantities/Astropy_Units.ipynb` :heavy_check_mark: 
- [x] `03-UnitsQuantities/Astropy_Units_Solutions.ipynb` :heavy_check_mark: 
- [x] `04-Coordinates/astropy_coordinates.ipynb` :heavy_check_mark: 
- [x] `04-Coordinates/astropy_coordinates_solutions.ipynb` :heavy_check_mark: 
- [x] `05-FITS/io_fits_ascii_overview.ipynb` :heavy_check_mark: 
- [x] `06-Tables/Advanced_Tables.ipynb` :heavy_check_mark: 
- [x] `06-Tables/Tables.ipynb` :heavy_check_mark: 
- [x] `06-Tables/Tables_solutions.ipynb` :heavy_check_mark: 
- [ ] `08-WCS/CCDData_tutorial.ipynb` :heavy_check_mark: 
- [ ] `08-WCS/Visualization_solutions.ipynb` :heavy_check_mark: 
- [ ] `08-WCS/Visualization_tutorial.ipynb` :heavy_check_mark: 
- [ ] `08-WCS/WCS_solutions.ipynb` :heavy_check_mark: 
- [ ] `08-WCS/WCS_tutorial.ipynb` :heavy_check_mark: 
- [ ] `09-Photutils/photutils_local_backgrounds.ipynb` :question:
- [ ] `09-Photutils/gaussian_psf_photometry.ipynb` :question:
- [ ] `09-Photutils/image_psf_photometry_withNIRCam.ipynb` :question:
- [ ] `09-Photutils/photutils_extended.ipynb` :question:
- [ ] `09-Photutils/photutils_overview.ipynb` :question:
- [ ] `09-Photutils/photutils_overview_solutions.ipynb` :question:
- [ ] `09b-Specutils/Specutils_analysis.ipynb` :x: 
- [ ] `09b-Specutils/Specutils_overview.ipynb` :x: 

Ignore these notebooks:

* `02-PythonIntro/*.ipynb`
* `07-Models/*.ipynb`

**Comment by pllim** [comment]
Ideally, copyedit should be the last step after we finalized the contents. But #90 is still open and is a blocker.

**Comment by pllim** [comment]
@adrn and @lglattly , exactly what sort of contents you have in mind for copy-editing? Slides, notebooks, or both? I think some are ready. I can make an inventory for you once I hear back. Thanks.

**Comment by adrn** [comment]
I was imagining notebooks first, but good point about slides. Maybe we can start with the notebooks and see how we do with time?

**Comment by pllim** [comment]
@adrn and @lglattly , I added the inventory in your original issue above. Hopefully relevant instructors can update it as appropriate. Hope this helps!

**Comment by lglattly** [comment]
Very helpful @pllim thank you!

**Comment by pllim** [comment]
Update from @bsipocz regarding the "Tables" section, "I suppose it’s copy editable state."

**Comment by lglattly** [comment]
I've made copy edits to the first group of "ready for copy editing" notebooks in this list 03-06 in pull request #126. One note that when the "solutions" file is very long (like in the case of the coordinates notebook) I'm not repeating the copy edits there since the text is all the same and it seems like people will only be looking at the solutions to the exercises in those files.

I can look at any of the other notebooks whenever they are ready!

**Comment by stargaser** [comment]
I merged the `08-WCS` notebooks and updated the checklist...probably too late for copy editing?

**Comment by pllim** [comment]
Given that we have less than 24 hours now, probably... 😬

**Comment by pllim** [comment]
We can still do this for future workshops. Removing milestone. FYI.

**Comment by lglattly** [comment]
Sorry I missed this, was on the flight yesterday! But yes, I can definitely copy edit these for future workshops!
