### ISSUE TITLE
TST: Fix CI failures

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-workshop#112]
Follow-up of #111 . Notebook owners need to see why their notebooks are failing and fix accordingly.

Blocked by #89 (specutils analysis)

**Comment by adrn** [comment]
Specifically, the two failing notebooks are: (specutils) Specutils_analysis.ipynb and (photutils) image_psf_photometry_withNIRCam.ipynb 

<sub>maybe it's because of the "utils" in the names 😄</sub>

**Comment by pllim** [comment]
specutils = @eteq 

photutils = @shannnnnyyy and/or @larrybradley

**Comment by pllim** [comment]
@adrn , I think the `photutils` one is actually `photutils_overview_solutions.ipynb`, not the NIRCam one? I proposed a fix for it at #116.

**Comment by pllim** [comment]
Linux passed now but Windows failed.
