### ISSUE TITLE
TST: Tag cells with expected exceptions

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-workshop#114]
As pointed out by @adrn in https://github.com/astropy/astropy-workshop/pull/111#issuecomment-566255799 .

When all notebooks are tagged, @adrn can turn on some magic to let CI fail when there is unexpected exceptions (see https://github.com/astropy/astropy-workshop/pull/111#issuecomment-566253509).

**Comment by pllim** [comment]
p.s. Hmm, when I got back to the Units notebook, it seems like the tags are already there. :woman_shrugging:

**Comment by adrn** [comment]
I tagged most of them in my PR! I just didn't fix the truly failing notebooks
