### ISSUE TITLE
Why do we require Glue?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-workshop#123]
This question is resulted from #120 . The original problem stemmed from installing `bottleneck` but it is not something we explicitly require, but rather a dependency of `glue-core`. Glue is a heavy-weight viz tool, which I don't see we use for AAS 235, do we? No notebook shows up as using it when I do a quick search on the GitHub search bar. Why is it in the `environment.yml` file?

**Comment by stargaser** [comment]
I think Glue is a holdover from previous workshops. Our README used to say that we'd answer questions about it. We've dropped that part of the README now, and we don't use it in the workshop. If our philosophy is that astropy core plus photutils, specutils, and their dependencies asdf and gwcs are lightweight enough to be installed on everyone's laptops, then we can remove Glue.

**Comment by stargaser** [comment]
I've removed Glue from the `environment.yml` file.
