### ISSUE TITLE
Update instructor photos in introductory slides

### ISSUE THREAD

**Issue by stargaser** [astropy/astropy-workshop#124]
In the slides in `01-IntroCoc`, there are headshots of all the facilitators. We need to update this for each workshop or else drop the photos.

**Comment by pllim** [comment]
I vote to drop them. We can stand up in the room during intro and they see our faces anyway.

**Comment by stargaser** [comment]
I also like the idea of dropping the photos and of introducing everyone at the start. The Trainer shirts are meant to identify us as facilitators at the workshop, and afterwards people can look at whatever image we've chosen to put on our Github profiles.

**Comment by pllim** [comment]
Is this going to happen before the workshop?

**Comment by eteq** [comment]
I found it pretty easy to do this via googling so just went ahead and updated them in 3a154a4db23b5537fae98d60b5979d20c75624f9 - I agree with @pllim and @stargaser that we should stand up *anyway*, but I'm not sure if everyone will be there at the outset so it seems safer to take just a moment to also see them on the screen.
