### ISSUE TITLE
Binder instances

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-workshop#136]
Main binder link: https://mybinder.org/v2/gh/astropy/astropy-workshop/master

Alternate: https://binder.flatironinstitute.org/v2/user/apricewhelan/aas-astropy

**Comment by pllim** [comment]
Are these going to be shut off tonight or something?

**Comment by adrn** [comment]
Nope! I can keep the flatiron one up indefinitely, and mybinder will stay available as long as we link to it.

**Comment by pllim** [comment]
I don't think it makes sense to keep this issue open. If you want, please add binder links to README at the root dir. I am closing this issue. Thanks!
