### ISSUE TITLE
think about automated testing the notebooks

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-workshop#14]

**Comment by kne42** [comment]
@stargaser and I have automated testing with Travis-CI and AppVeyor set up in [our data visualization tutorial](https://github.com/kne42/data-visualization-tutorial).

You can use that as a reference while making your own or I can help set it up for you.

We also have scripts to allow having hidden solution and markdown cells.

**Comment by kne42** [comment]
We are also refining a custom pytest configuration that will read and run all notebooks in a specified directory. It is recommended to run this on your "solution" notebooks to ensure that all of the follow-alongs and exercises work on each platform.

While I will probably turn this into a full-fledged plugin at some later time, the source code can be found [here](https://github.com/kne42/data-visualization-tutorial/blob/notebook-pytest/conftest.py).

**Comment by pllim** [comment]
As discussed during Astropy Coordination Meeting 2019, @adrn will take a stab at this to kill two birds with one stone: Making sure notebook works and have rendered HTML available.
