### ISSUE TITLE
Update WCS tutorial to use APE14-style wcs methods

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-workshop#140]
while @stargaser was going through the WCS tutorial, @larrybradley and I noticed it's using the "old" way of interacting with WCS `wcs_world2pix`/`wcs_pix2world` instead of the newer and better APE14 `world_to_pixel` and `pixel_to_world` machinery.  The notebook should be updated for that for future workshops.

**Comment by stargaser** [comment]
fixed in #156.
