### ISSUE TITLE
Update "modeling" lesson for Astropy 4.0

### ISSUE THREAD

**Issue by eblur** [astropy/astropy-workshop#144]
I heard that the Astropy modeling package was refactored for Astropy 4.0. We need to check and update the [modeling lesson module](https://github.com/astropy/astropy-workshop/tree/master/07-Models) for this new behavior.

**Comment by stargaser** [comment]
This has been dropped for time.

**Comment by eblur** [comment]
Modelling was dropped from the program to stay within the allotted time.
