### ISSUE TITLE
Tell people how to do a git pull with modified notebooks

### ISSUE THREAD

**Issue by stargaser** [astropy/astropy-workshop#15]
Here is an issue that I was asked about several times. The participant has been working on notebooks all day. They realize that they need to do a git pull to do the latest. At AAS231 I think this was needed to make up for missing data files. (Side note: #14 would save us from missing data files, I think.)

I had to ask @sosey for "best practices" advice, which I recall as, tell the participant to do a "git stash", and then "git pull". I recommend this go into the README as a section like "if you need a git pull in the middle of the workshop..."

**Comment by sosey** [comment]
yah, it was easiest to have them stash their current stuff and pull the updated repo. The next would have been "git stash pop" to merge their changes with the updates, but then if they modified the notebooks in some conflicting way they'd have to resolve conflicts.... We should document a better way to do this at a point where their local repositories have changes. 

What may be better, as part of helping them develop a good git workflow,  is to show them how to create a branch at the beginning of the workshop and then have them work in that branch. Preferably using something like `git checkout -b my-local-branch origin/master` along with perhaps how to do a hard reset of your local copy if they just want to overwrite their changes `git fetch` followed by `get reset --hard  origin/master`

**Comment by eteq** [comment]
Closed by #41
