### ISSUE TITLE
Broken link to simulated JWST/NIRCam data in image_psf_photometry_withNIRCam 

### ISSUE THREAD

**Issue by stargaser** [astropy/astropy-workshop#151]
**Describe the bug**
In the photutils notebook `image_psf_photometry_withNIRCam.ipynb`, an HTTP Error 404: Not Found is raised at the point when simulated data are downloaded.

**To Reproduce**
With the workshop environment installed, execute the `image_psf_photometry_withNIRCam` notebook.

**Expected behavior**
The download should succeed and the notebook should execute from beginning to end.

**Screenshots**

**Desktop (please complete the following information):**
Used a "launch:binder" link from https://github.com/stargaser/workshop-env to launch my session.

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pllim** [comment]
If I remember correctly, @eteq should know how to fix this.

**Comment by stargaser** [comment]
@larrybradley might know the right link?

**Comment by larrybradley** [comment]
Yes, I'll take a look.

**Comment by larrybradley** [comment]
I've fixed this.  The links in the notebook are correct, but the permissions in the STScI Box folder were wrong.  The notebook is working again (no changes needed to the notebook).
