### ISSUE TITLE
Problems reading SDSS spectrum in Specutils_overview notebook.

### ISSUE THREAD

**Issue by stargaser** [astropy/astropy-workshop#155]
**Describe the bug**
Exceptions are raised in the Specutils_overview notebook when downloading and reading in the SDSS spectrum with plate=1323, mjd=57297, fiberid=12.  The Specutils_analysis notebook uses this same spectrum and fails as well.

**To Reproduce**
1. Install the workshop environment
2. Execute the Specutils_overview notebook to the "Loading spectra from files" section
3. The exceptions vary between specutils=1.0 and specutils=1.1.

**Expected behavior**
The notebooks should execute successfully.

**Desktop (please complete the following information):**
 - The error occurs in continuous integration in the test_linux job. [Example](https://app.circleci.com/pipelines/github/astropy/astropy-workshop/128/workflows/0e9fa602-2424-4c57-ba61-8267ebf8558e/jobs/165)

**Additional context**
This sample spectrum download appears in the [specutils Getting Started](https://app.circleci.com/pipelines/github/astropy/astropy-workshop/128/workflows/0e9fa602-2424-4c57-ba61-8267ebf8558e/jobs/165) documentation.

I have tried using astroquery.sdss to download this same spectrum, and it returns an empty result. I've tried using astroquery.sdss to download another spectrum in its documentation (plate=751, mjd=52251, fiberID=160); that returns a result, but when I save that to "data/sdss_spectrum.fits", it does not work with these notebooks.

**Comment by eteq** [comment]
I'm hoping to get in a quick release of specutils to just fix this one thing, but if not the fallback is @pllim's suggestion.  

Either way, though, the SDSS servers are down and I'm getting some guidance that this spectrum is not the best choice because it's not in some of the backup servers.  So I'm investigating changing the URL at the same time as fixing the example.
