### ISSUE TITLE
[Question] error in "python check_env.py" stage

### ISSUE THREAD

**Issue by vpkulkarni** [astropy/astropy-workshop#160]
**Which workshop are you signed up for?** beginners and advanced

**What is your operating system?** Mac OS 10.13.4

**Describe your question/problem**
Hello, I followed the instructions to install the necessary software for the beginners workshop, but  I am getting some errors while running python check_env.py.  It doesn't seem to be a question of mismatching versions, but I am not sure what to do. I also tried "pip install astropy --upgrade", but that just confirmed that the numpy and pyerfa requirements were already satisfied, and made no difference.  Please take a look at the following and let me know as soon as possible. Thanks.

(astropy-workshop) Varshas-Air:00-Install_and_Setup kulkarni$ python check_env.py
Found IPython 7.19.0
Found cython 0.29.21
Found jupyter 
Found notebook 6.1.6
Found numpy 1.19.2
Found scipy 1.5.2
Found skimage 0.17.2
Found matplotlib 3.3.2
Found pandas 1.2.0
Found bs4 4.9.3
Found keyring 
Found html5lib 1.1
Found xlwt 1.3.0
Found xlrd 2.0.1
Found requests 2.25.1
Found jupyterlab 3.0.1
Found nbgitpuller 0.9.0
Traceback (most recent call last):
  File "check_env.py", line 75, in <module>
    run_checks()
  File "check_env.py", line 66, in run_checks
    errors.append(check_package(package_name, minimum_version=min_version))
  File "check_env.py", line 41, in check_package
    pkg = __import__(package_name)
  File "/Users/kulkarni/anaconda3/envs/astropy-workshop/lib/python3.8/site-packages/astropy/__init__.py", line 248, in <module>
    _initialize_astropy()
  File "/Users/kulkarni/anaconda3/envs/astropy-workshop/lib/python3.8/site-packages/astropy/__init__.py", line 218, in _initialize_astropy
    config.configuration.update_default_config(__package__, config_dir)
  File "/Users/kulkarni/anaconda3/envs/astropy-workshop/lib/python3.8/site-packages/astropy/config/configuration.py", line 835, in update_default_config
    with open(template_path, 'wt', encoding='latin-1') as fw:
PermissionError: [Errno 13] Permission denied: '/Users/kulkarni/.astropy/config/astropy.4.2.cfg'
(astropy-workshop) Varshas-Air:00-Install_and_Setup kulkarni$

**Comment by stargaser** [comment]
I think what is happening is, when “import astropy” is executed in a Python session, astropy tries to open this config file. I expect that if you start a plain Python session, “import astropy” just fails. 

What are the permissions on `/Users/kulkarni/.astropy/config/astropy.4.2.cfg`? You can change these with, I think, `chmod -R u+rw /Users/kulkarni/.astropy`.

It looks like all the conda packages got installed fine, and maybe it is “pip” that has installed things without the right permissions?

**Comment by vpkulkarni** [comment]
Thank you for the reply. It looks like there is no /Users/kulkarni/.astropy/config/astropy.4.2.cfg. 
There is a astropy.4.0.cfg, so does that mean I need to install astropy4.2? I did try to upgrade astropy (see below), but that didn't seem to do anything, and gave the same errors on running check_env.py 

Please let me know if you have any other suggestions. 
Thanks so much!

**Comment by vpkulkarni** [comment]
Hi David,

(I also sent the same in the issue tracker as a comment; please pardon the
duplication.)

Thank you for the reply. It looks like there is no
/Users/kulkarni/.astropy/config/astropy.4.2.cfg.

There is a astropy.4.0.cfg, so does that mean I need to install astropy4.2?
I did try to upgrade astropy (see below), but that didn't seem to do
anything, and gave the same errors on running check_env.py

Please let me know if you have any other suggestions.

Thanks so much!
Varsha


(astropy-workshop) Varshas-Air:00-Install_and_Setup kulkarni$ pip install
astropy --upgrade
Requirement already satisfied: astropy in
/Users/kulkarni/anaconda3/envs/astropy-workshop/lib/python3.8/site-packages
(4.2)
Requirement already satisfied: numpy>=1.17 in
/Users/kulkarni/anaconda3/envs/astropy-workshop/lib/python3.8/site-packages
(from astropy) (1.19.2)
Requirement already satisfied: pyerfa in
/Users/kulkarni/anaconda3/envs/astropy-workshop/lib/python3.8/site-packages
(from astropy) (1.7.1.1)
(astropy-workshop) Varshas-Air:00-Install_and_Setup kulkarni$

On Wed, Jan 6, 2021 at 4:55 PM David Shupe <notifications@github.com> wrote:

> I think what is happening is, when “import astropy” is executed in a
> Python session, astropy tries to open this config file. I expect that if
> you start a plain Python session, “import astropy” just fails.
>
> What are the permissions on
> /Users/kulkarni/.astropy/config/astropy.4.2.cfg? You can change these
> with, I think, chmod -R u+rw /Users/kulkarni/.astropy.
>
> It looks like all the conda packages got installed fine, and maybe it is
> “pip” that has installed things without the right permissions?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://protect2.fireeye.com/v1/url?k=54a546dc-0b3e7e27-54a5081d-8685f1c04bc5-89de44d3d2fff7dc&q=1&e=3f61fb31-8224-4718-809c-55a763bbdf71&u=https%3A%2F%2Fgithub.com%2Fastropy%2Fastropy-workshop%2Fissues%2F160%23issuecomment-755737272>,
> or unsubscribe
> <https://protect2.fireeye.com/v1/url?k=07342e92-58af1669-07346053-8685f1c04bc5-cfcb7fab1bd6c5cb&q=1&e=3f61fb31-8224-4718-809c-55a763bbdf71&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIM2WUQBDSJWT64GNVMLAM3SYTL6NANCNFSM4VYCWWYQ>
> .
>


-- 
**********************************************
Varsha P. Kulkarni, Ph.D.
Professor, Department of Physics and Astronomy
University of South Carolina
Columbia, SC 29208
Tel.    (803)-777-6293
FAX     (803)-777-3065
E-mail kulkarni@sc.edu
URL: http://boson.physics.sc.edu/~kulkarni/
**********************************************

**Comment by stargaser** [comment]
It looks like astropy 4.2 is installed properly. You can check with `conda list astropy`.

I think this is a permissions issue with `/Users/kulkarni/.astropy/config`. Would you please check if you can write a file there? Or try `ls -l /Users/kulkarni/.astropy/config`. If you don't have write permission, that would be the thing to fix with `chmod u+rwx /Users/kulkarni/.astropy/config`.

It appears to me you had successfully installed and imported astropy v4.0 before, since that config file exists...but perhaps with different file permissions.

**Comment by vpkulkarni** [comment]
Thanks. It seems to be working now.

On Wed, Jan 6, 2021 at 5:45 PM David Shupe <notifications@github.com> wrote:

> It looks like astropy 4.2 is installed properly. You can check with conda
> list astropy.
>
> I think this is a permissions issue with /Users/kulkarni/.astropy/config.
> Would you please check if you can write a file there? Or try ls -l
> /Users/kulkarni/.astropy/config. If you don't have write permission, that
> would be the thing to fix with chmod u+rwx /Users/kulkarni/.astropy/config
> .
>
> It appears to me you had successfully installed and imported astropy v4.0
> before, since that config file exists...but perhaps with different file
> permissions.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://protect2.fireeye.com/v1/url?k=5d26ae11-02bd96c5-5d26e0d0-860a66ff9d26-bf99fe19a5bbf71d&q=1&e=2fed0cf9-ce68-43f9-bff3-7b39dbc1cc62&u=https%3A%2F%2Fgithub.com%2Fastropy%2Fastropy-workshop%2Fissues%2F160%23issuecomment-755762510>,
> or unsubscribe
> <https://protect2.fireeye.com/v1/url?k=c19df240-9e06ca94-c19dbc81-860a66ff9d26-fce835179c77c0d8&q=1&e=2fed0cf9-ce68-43f9-bff3-7b39dbc1cc62&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIM2WUSZSQNXTBRBXD6PCJTSYTRWTANCNFSM4VYCWWYQ>
> .
>


-- 
**********************************************
Varsha P. Kulkarni, Ph.D.
Professor, Department of Physics and Astronomy
University of South Carolina
Columbia, SC 29208
Tel.    (803)-777-6293
FAX     (803)-777-3065
E-mail kulkarni@sc.edu
URL: http://boson.physics.sc.edu/~kulkarni/
**********************************************

**Comment by vpkulkarni** [comment]
Thanks. It seems to be working now.
