### ISSUE TITLE
Some of us are real beginners.  Could you demonstate the commands that are needed.. For example, i am in a jupyter notebook and am totally lost what commands to use.

### ISSUE THREAD

**Issue by peterrothstein45** [astropy/astropy-workshop#162]
**Which workshop are you signed up for?**

**What is your operating system?**

**Describe your question/problem**

**Comment by peterrothstein45** [comment]
Astropy for beginners
Mac OS
Some of us are real beginners. Could you demonstate the commands that are needed.. For example, i am in a jupyter notebook and am totally lost what commands to use.

**Comment by kelle** [comment]
What are you trying to do? Have you tried to do the Install and Setup instructions: https://github.com/astropy/astropy-workshop/tree/main/00-Install_and_Setup
If you are in the AAS Meeting slack workspace, it might be easier to chat in the "workshop_into_to_astropy_beginners" channel.

**Comment by peterrothstein45** [comment]
i am trying to follow the instructions.

 If you have any problems with any of these steps, please check if your problem has already been reported at the issue tracker <https://github.com/astropy/astropy-workshop/issues/>. If not, ask your question in the issue tracker <https://github.com/astropy/astropy-workshop/issues/new?assignees=&labels=workshop-question&template=question-from-workshop-participant.md&title=%5BQuestion%5D+Summarize+your+question+here>.

**Comment by kelle** [comment]
Step 1 of the instructions should be executed from the command line, not from within a Jupyter notebook.  (You don't need to open a Jupyter notebook until Step 5.)  Have you run this command from the command line: `git clone https://github.com/astropy/astropy-workshop.git`?

**Comment by pllim** [comment]
FWIW, for learning how to use the notebook itself, there are other resources out there, such as https://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/ . Hope this helps!

**Comment by larrybradley** [comment]
Just to add a quick note -- once you are in a notebook, "Shift+Enter" will execute a cell and then move to the next cell.
