### ISSUE TITLE
polish Install and Setup

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-workshop#165]
- Readme Title should be consistent with folder name. E.g., change Readme title to "Setup and Install Instructions for Workshop"
- make it even more clear where commands should be typed (e.g., in Terminal vs in Jupyter Notebook).
- make it even more clear what directory one should be in when typing commands. e.g., add `cd` and/or `pwd` commands.
- be explicit about which directory to be in when opening the notebook.

**Comment by stargaser** [comment]
To add to the list: a bash shell is no longer needed to use conda.

**Comment by eblur** [comment]
Need install instructions to address zsh setup in new Mac OS

**Comment by mwcraig** [comment]
Steps to deal with zsh:

```
source /path/to/conda/bin/activate
conda init zsh
```

Then open a new terminal window and `conda list` should give some kind of sensible output.

**Comment by kelle** [comment]
also consider adding something about 32-bit/64-bit discussed in #54.

**Comment by kelle** [comment]
Copied and pasted from #170: Give conda environment a different name:

The workshop repository is named astropy-workshop and the conda environment has the same name. When changes need to be pulled from the repository, and new packages or updated packages need to be installed into the conda environment, it is easy to conflate these two locations.

Change the conda environment name to something different, like astropy-env.
