### ISSUE TITLE
Use different names for the conda environment and the repository name

### ISSUE THREAD

**Issue by stargaser** [astropy/astropy-workshop#170]
**Is your feature request related to a problem? Please describe.**
The workshop repository is named `astropy-workshop` and the conda environment has the same name. When changes need to be pulled from the repository, and new packages or updated packages need to be installed into the conda environment, it is easy to conflate these two locations.

**Describe the solution you'd like**
Change the conda environment name to something different, like `astropy-env`.

**Describe alternatives you've considered**
We could not use conda environments. The workshop materials could be frozen before the participants receive installation instructions.

**Additional context**

**Comment by kelle** [comment]
Added to #165
