### ISSUE TITLE
Write install instructions for Windows machine (Windows 10)

### ISSUE THREAD

**Issue by eblur** [astropy/astropy-workshop#175]
(Based on participant feedback) - we need to write installation instructions for Windows 10

**Comment by kelle** [comment]
I hear that @stargaser and @eteq discussed this. Could you please post an update in this issue?

**Comment by eblur** [comment]
We discussed this during the Learn telecon and noted from the Slack discussion in #workshop-planning:

"For windows users we will recommend/support WSL"

This sounds like a good plan! We also learned that many windows users have issues with git, so perhaps we should recommend that Windows user download the latest workshop repo as a zipfile instead of having them use git to get the latest updates.

**Comment by stargaser** [comment]
WSL instructions were added in #200.
