### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by nancymac519** [astropy/astropy-workshop#187]
**Describe the bug**
After following the instructions to install the workshop materials, I ran the check_env.py script and got a long list of missing packages. I tried installing a couple with 'condo install package name' and it seemed to work, but it will take me a while to install all of them by hand.

**To Reproduce**
Steps to reproduce the behavior: command line --
1. $ git clone https://github.com/astropy/astropy-workshop.git
2. $ cd astropy-workshop/00-Install_and_Setup/
3. conda env create --file environment.yml 
4. conda activate astropy-env
5. python check_env.py
6. see error messages in output
Found IPython 7.22.0
Found cython 0.29.23
Found jupyter 
Found notebook 6.4.0
Found numpy 1.20.2
Found scipy 1.6.2
Found skimage 0.18.1
Found matplotlib 3.3.4
Found pandas 1.2.4
Error: Failed import: No module named 'bs4'
Error: Failed import: No module named 'keyring'
Error: Failed import: No module named 'html5lib'
Error: Failed import: No module named 'xlwt'
Error: Failed import: No module named 'xlrd'
Error: Failed import: No module named 'requests'
Error: Failed import: No module named 'jupyterlab'
Error: Failed import: No module named 'nbgitpuller'
Found astropy 4.2.1
Error: Failed import: No module named 'asdf'
Error: Failed import: No module named 'gwcs'
WARNING: AstropyDeprecationWarning: block_reduce was moved to the astropy.nddata.blocks module.  Please update your import statement. [astropy.nddata.utils]
WARNING: AstropyDeprecationWarning: block_replicate was moved to the astropy.nddata.blocks module.  Please update your import statement. [astropy.nddata.utils]
Found ccdproc 2.1.0
Error: Failed import: No module named 'photutils'
Error: Failed import: No module named 'specutils'
Error: Failed import: No module named 'astroquery'

There are errors that you must resolve before running the tutorials.

**Expected behavior**
No errors
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS 10.13.6
 - Browser [e.g. chrome, safari] Safari 
 - Version [e.g. 22] 13.1.2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by stargaser** [comment]
Thank you for creating an issue for this. Some of the packages are intended to be installed with `pip` instead of with `conda`.

In a terminal, what does `which pip` return?

Does `pip install specutils photutils astroquery` work?

**Comment by nancymac519** [comment]
Hi David,

Thanks for the tip. To answer your questions:

'which pip' returns: /Users/gwen/opt/anaconda3/envs/astropy-env/bin/pip

Yes, the install command you provided works. I also used it to install the remaining missing packages, and 'check_env.py' now returns:
'Your Python environment is good to go!'

I do get some warnings: 

'WARNING: AstropyDeprecationWarning: block_reduce was moved to the astropy.nddata.blocks module.  Please update your import statement. [astropy.nddata.utils]
AstropyDeprecationWarning: block_reduce was moved to the astropy.nddata.blocks module.  Please update your import statement.
WARNING: AstropyDeprecationWarning: block_replicate was moved to the astropy.nddata.blocks module.  Please update your import statement. [astropy.nddata.utils]
AstropyDeprecationWarning: block_replicate was moved to the astropy.nddata.blocks module.  Please update your import statement.'

Thanks,
Nancy



________________________________________
From: David Shupe ***@***.***>
Sent: Thursday, May 27, 2021 4:16 PM
To: astropy/astropy-workshop
Cc: Morrison, Nancy D.; Author
Subject: [EXTERNAL] Re: [astropy/astropy-workshop] Missing packages (#187)

Thank you for creating an issue for this. Some of the packages are intended to be installed with pip instead of with conda.

In a terminal, what does which pip return?

Does pip install specutils photutils astroquery work?

**Comment by stargaser** [comment]
I'm glad that worked @nancymac519!  Thank you for working through it.

The AstropyDeprecationWarnings are not important. Others have noticed these too. For some reason they do not appear when I run `python check_env.py` on my Mac.
