### ISSUE TITLE
'python check_env.py': Two Astropy Deprecation warnings

### ISSUE THREAD

**Issue by MarioHummer** [astropy/astropy-workshop#188]
**Which workshop are you signed up for?**
astropy
**What is your operating system?**
MacOS 10.13.6
**Describe your question/problem**
When checking my Python environment, the 'python check_env.py' command gave two Astropy Deprecation Warnings wrt block_reduce & block_replicate.
Anything to worry about?
Thank you.

**Comment by stargaser** [comment]
Thank you for posting this question. These Astropy Deprecation Warnings are not a problem for this workshop.

**Comment by larrybradley** [comment]
@MarioHummer You don't need to worry about those deprecation warnings.

**Comment by MarioHummer** [comment]
@stargaser @larrybradley Thank you for your prompt feedback. See you at the workshop.
