### ISSUE TITLE
Update the conda environment with latest astropy and astroquery

### ISSUE THREAD

**Issue by stargaser** [astropy/astropy-workshop#197]
I think we should update astropy to the new LTS 5.0 release, and update astroquery as well. These should be minimum versions.

For the NAVO workshop the day after this one at AAS 239, that's what we decided, but then we do not use photutils, ccdproc or specutils. So we would want to make sure that those work with astropy 5.0, or else we should stick with 4.3.1.

**Comment by wtgee** [comment]
I bumped astropy to 5.0 for AAS 239 https://github.com/stargaser/workshop-env/pull/1

**Comment by stargaser** [comment]
The minimum versions were updated.
