### ISSUE TITLE
Brief tutorial of the time module

### ISSUE THREAD

**Issue by bmorris3** [astropy/astropy-workshop#204]
**Is your feature request related to a problem? Please describe.**

It looks like we only mention the Time module tangentially, for example, in an AltAz transformation in the [coordinates module](https://github.com/astropy/astropy-workshop/blob/main/04-Coordinates/astropy_coordinates.ipynb) and QTables in [tables](https://github.com/astropy/astropy-workshop/blob/e9af888db0d8e93c3cf0a51461a333525bdcf2b1/06-Tables/Tables.ipynb). 

Is there any interest in a pull request with a small tutorial on the Time object? I'm happy to do it.

**Describe the solution you'd like**
I think it would make sense to very briefly describe the Time module in the coordinates module, and explain the transformations you can make.

**Describe alternatives you've considered**
Alternatively we could do a whole module on time, but that doesn't seem necessary. 

**Additional context**
I'm prepping for a small astropy workshop in Madrid, and there have been requests to directly address time.

**Comment by stargaser** [comment]
The time tutorial was added in #205.
