### ISSUE TITLE
Command "mamba" is not found

### ISSUE THREAD

**Issue by stargaser** [astropy/astropy-workshop#222]
At least three users reported that the `mamba info` step in the instructions just brought up an error that the mamba command is not found.

The solution is to specify the full path to mamba, e.g. `$HOME/bin/mamba info`, or `$HOME/bin/mamba init` to initialize the user's shell.

**Comment by stargaser** [comment]
Now that the libmamba solver is included in conda by default, we could switch the instructions back to conda...

**Comment by bmorris3** [comment]
I don't know the history of how we got here – do we want that? 

My preferred approach is to have users: 
* install miniconda
* make an astropy workshop environment with a recent python
* use `pip install -r requirements.txt` to install _every_ dependency

That's been the fastest way to get people up and running in my recent experience. Is there any reason that isn't sufficient for this workshop?

**Comment by stargaser** [comment]
This history of how we got here is that several years ago, users were just told to install Anaconda since it included astropy and Jupyter notebooks. Then for the AAS 235 workshop in January 2020, we switched to a full-blown conda install, IIRC.

I like your preferred approach. It would make everything a lot simpler. Let's do it!
