### ISSUE TITLE
ALOHA-2024 reorg

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-workshop#252]
- [x] Cherry pick https://github.com/astropy/astropy-workshop/pull/249 to ALOHA-2024 branch from main.
- [x] Re-organize ALOHA-2024 branch so it is more relevant to the actual workshop. #254

**Comment by pllim** [comment]
@mwcraig , once you cherry picked that commit, feel free to close this issue. Thanks!

**Comment by mwcraig** [comment]
I did the cherry pick directly to the ALOHA branch and pushed it before the reorg
