### ISSUE TITLE
be consistent with the use of matplotlib magics, or explain the difference

### ISSUE THREAD

**Issue by sosey** [astropy/astropy-workshop#26]
The notebooks have a mix of matplotlib magics, notebook vs inline, it might be good to either have a short section explaining the difference, or comments around the sections those magics appear, or teach from a common command so that it's not confusing for those who are new to matplotlib and notebooks.

**Comment by kelle** [comment]
Heads up @shannnnnyyy , @eteq , and @bmorris3

**Comment by JuanCab** [comment]
I went ahead and added a short discussion of matplotlib magic commands to the jupyter notebook introduction in PR #34

**Comment by JuanCab** [comment]
I think we can close this, given the merger of #34
