### ISSUE TITLE
update nircam phot notebook with better imexam example

### ISSUE THREAD

**Issue by sosey** [astropy/astropy-workshop#29]
The example in this notebook: https://github.com/astropy/astropy-workshop/blob/master/09-Photutils/image_psf_photometry_withNIRCam.ipynb can be updated with a better imexam example showing how to view and mark the stars using either `ds9`, a `ginga` window, or no viewer at all, just a return of the marked up image.

**Comment by kelle** [comment]
Just looping in @eteq since he will likely be leading this session.

**Comment by JuanCab** [comment]
The package `imexam` is *NOT* currently installed by the `environment.yml`.  Pull request #31 will fix this.

**Comment by sosey** [comment]
you should install imexam 0.8.1, not 0.8.0 as I just saw in the last PR I was pinged on, let me know if you still see the error after that.

**Comment by JuanCab** [comment]
The error on launching ds9 is being returned using imexam 0.8.1!  It launches the X11 version ds9 (I have the macOS app and the x11 app of ds9 version 8.0 installed) and then locks up.

**Comment by JuanCab** [comment]
I did tweak my PR #31 to force `imexam` to version 0.8.1 or newer.

**Comment by sosey** [comment]
when you say locks up, do you mean it never connects, or it goes into a hard lock you have to quit out of ds9, or worse, the x11 servers for ds9 continually tries to restart itself? There's a known bug in the current install of x11 quartz to OSX high sierra+ that causes server issues. 🤦‍♀️ I can't remember the fix off the top of my head, I think it was a link to the location of the plist, but I had to do it a couple weeks ago myself...let me look tomorrow at work, I can't replicate your issue currently on my osx

**Comment by sosey** [comment]
ugh...on my brand new mac laptop running 10.13.6...with a giant trackpad that if I accidentally touch closes issues 🤦‍♀️

**Comment by JuanCab** [comment]
It launches the X11 version of ds9 (and the window title bar suggest imexam is trying to set the display contents), but then in Jupyter notebooks it reports the error `XpaException: Unknown XPA Error : XPAGet returned 0!` and the connection is never completed (and the Jupyter cell crashes out).

**Comment by sosey** [comment]
@JuanCab I pulled the updated notebook and env, the `imexam` issue in the nircam notbook is that all those commands are in the same cell. Put the import and connect command by themselves in the cell above. This give the server time to startup and connect before trying to contact it again to post the image..it's a timing issue. When I did that I had no problems.

**Comment by sosey** [comment]
add a line with `imex.scale()` as well so the image appears nicely zscaled...
<img width="1147" alt="screen shot 2019-01-01 at 9 47 12 pm" src="https://user-images.githubusercontent.com/503615/50579001-ec66c580-0e0e-11e9-90ee-7ca932c15bb7.png">

**Comment by JuanCab** [comment]
Still getting the same XPA error, despite splitting the calls to connect and load the fits file.

**Comment by sosey** [comment]
okay..this might be the plist issue as well for you. I got the XPA error you posted myself, but splitting the cells fixed it. Let me find the fix again for that tomorrow and I'll post here, if students try this they may also need to implement the fix

**Comment by JuanCab** [comment]
OK, I have also disabled the X11 version (since I noticed you appeared to be running the native macOS app), and it can't find that ds9.  Not sure why...

**Comment by sosey** [comment]
hmm, I'm running 
>ds9                       7.6                           0    http://ssb.stsci.edu/astroconda

**Comment by JuanCab** [comment]
But is that a macOS native-app or an X11 app?

**Comment by sosey** [comment]
we'll figure it out tomorrow..or just remove the imexam example for now since there aren't any other notebooks planned to demonstrate......yah, that's the x11 app, not the quartz app.

**Comment by JuanCab** [comment]
I just looked at that AstroConda tarball, it looks like it has a bunch of xpaaccess related binaries not in the SAOImage tarball. I am checking to see if all I need is the XPA files from SAO.  Actually, that fixed the connection, I got another error, but I suspect that is because there is a space in the full pathname.  Sure enough that fixed it!  So the problems were:
1. While I had the X11 version of ds9 installed, I had not installed the XPA access files.
2. My directory containing the notebook has a space in the full pathname.

Once I fixed those two things, it worked.

**Comment by JuanCab** [comment]
Pull Request #33 is an attempt to clarify the use of `imexam` in this notebook.

**Comment by sosey** [comment]
You shouldn't need to install the XPA access files with imexam and the x11 version of ds9. With those things are installed in the workshop environment and you should see them in the bin:

> /Users/sosey/miniconda3/envs/astropy-workshop/bin/xpaaccess	/Users/sosey/miniconda3/envs/astropy-workshop/bin/xpamb
> /Users/sosey/miniconda3/envs/astropy-workshop/bin/xpaget	/Users/sosey/miniconda3/envs/astropy-workshop/bin/xpans
> /Users/sosey/miniconda3/envs/astropy-workshop/bin/xpainfo	/Users/sosey/miniconda3/envs/astropy-workshop/bin/xpaset

imexam has it's own copy of the xpa, but it will use the ds9 installed ones in the directory above.  When you "conda install ds9" those binaries should show up.  You should not have to install them separately at all. The xpa binaries were probably removed when you uninstalled the x11 ds9.

There's should be no problem using the Quartz Ds9 app with the xpa installed with x11 ds9. However, the version mismatch between what's available on the conda channels and the quartz download seems to be a problem for me and the installed xpa is giving me errors in that case. 

I think the best path forward is to use the x11 ds9 v7.5/6 as installed and work from there since no extra effort on the part of the students is necessary.

**Comment by JuanCab** [comment]
Oh, OK, I need to make something clear.  We changed the workshop environment to NOT include ds9 (from astroconda).  This was partly done because it made installation on windows more simple and ensured the same environment on windows/macos/linux.  Do we need to cover `imexam` at the astropy workshop on Sunday?  If so, we need to change the installation instruction to include ds9 again.  The other choice is to switch to using `ginga` as the default viewer, since it works on all platforms using the astropy/conda-forge channels.  I understand `ginga` is less powerful, but for the workshop, I suspect it would be enough.

**Comment by sosey** [comment]
Yah, I've been having a hard time telling what the final decision on the workshop inclusions are....but I think it's cleaner to remove the cells with imexam from the nircam phot notebook, since nothing else in imexam is being demoed, it's just distraction.  If you decide not to, then you can keep the environment file as it is, without imexam, and without d9 or ginga, then in the optional section just tell them to "conda install imexam=0.8.1" and "conda install ds9" and it should be good.

**Comment by JuanCab** [comment]
`conda install ds9` doesn't work in the default environment because astroconda is NOt included and ds9 doesn't appear to be part of either astropy or conda-forge.

**Comment by JuanCab** [comment]
I did move `imexam` to the end of the workbook and mark it as optional.  I can also remove it if you think that is cleanest (I will revise the instructions about ds9 shortly, maybe I can add the notes about adding ds9 using astroconda, at least on macos).

**Comment by JuanCab** [comment]
OK, in view of the discussion on PR #33, I removed `imexam` completely from the notebook.  That doesn't really "resolve" the quest for a better `imexam` example, but since merging PR #33 also removes `imexam` from the default astropy-workshop environment for now, I suspect this closes this issue for now.

**Comment by sosey** [comment]
solved in https://github.com/astropy/astropy-workshop/pull/33
