### ISSUE TITLE
failed import: astroquery 

### ISSUE THREAD

**Issue by jweston1123** [astropy/astropy-workshop#3]
When I run the environment check, I get the error:
           ` Error: Failed import: No module named 'astroquery'`

I'm running anaconda2 for python 2.7 on a Mac. Otherwise had no installation problems.

**Comment by kelle** [comment]
quick thoughts:
I think you should be using the anaconda that includes python 3. you can always make a 2.7 environment. try updating your anaconda.

A couple of us are planning to be in the lobby bar around 9pm. Otherwise, please come at 8:30am for setup help.

**Comment by jweston1123** [comment]
Updating to Anaconda3 for python3 worked, so I'm good to go!
