### ISSUE TITLE
Apparently, there is no 32-bit Windows version of photutils

### ISSUE THREAD

**Issue by JuanCab** [astropy/astropy-workshop#54]
Installation instructions fail is someone is running 32-bit version of Anaconda.  Easy to accidentally do.  We should revise instructions to say to make sure to install 64-bit version of anaconda.

**Comment by bsipocz** [comment]
alternatively `pip install photutils` should work even on those systems

**Comment by bsipocz** [comment]
(We do test photutils on 32bit linux, but not on windows, so your suggestion of making sure 64bit conda is used is preferable though)

**Comment by JuanCab** [comment]
Yeah, I figured anyone using Windows 7 or 10 is almost certainly using a 64-bit version of those OSes on a computer less than 5 years old, so the 64-bit option is preferable. We had a workshop participant who installed the 32-bit version of Miniconda on a 64-bit Windows, and then had an issue with the environment not resolving because the 32-bit windows version of `photutils` is NOT in the `astropy` channel.

**Comment by pllim** [comment]
cc @larrybradley

**Comment by larrybradley** [comment]
Conda-forge stopped support for 32-bit windows (https://github.com/conda-forge/staged-recipes/issues/5640).  The anaconda astropy channel simply mirrors conda-forge. 

For 32-bit windows systems, one will need to install using `pip` (there's even a wheel for Win 32).

**Comment by bsipocz** [comment]
Maybe it would pedagogically make sense to pip install everything after conda creating the env? Transferable skill for the case when a package is not conda available.

**Comment by stargaser** [comment]
In #186 we're now requesting participants to install a 64-bit version of Miniconda.

**Comment by larrybradley** [comment]
Thanks, @stargaser.  I'm closing this issue now.  If ever needed, there are 32-bit windows wheels available via `pip`.
