### ISSUE TITLE
Should give more time for python "crash course" or not plan to actually go through it

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-workshop#55]
The material in the "Intro to Python" is good, but it's more than 30 min worth of material when actually gone-through.  For future workshops it it probably best to either allocate more time, or make it explicit what has happened in practice for the last two: we will go through the first 2 on running ipython and jupyter (since those are absolutely necessary to do the rest of the workshop), and otherwise we should say "do in advance, or as you have time"

**Comment by kelle** [comment]
yes, this was originally longer but it got cut due to the scheduling snafu.

**Comment by pllim** [comment]
No longer relevant given the conclusion from #59.
