### ISSUE TITLE
Drop Python Intro

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-workshop#59]
Consider dropping Python Intro and rearranging schedule accordingly. 

Instead, send folks pre-req materials to be sure they have some Python Intro ahead of time. (I'll make a new issue for that.)

**Comment by eteq** [comment]
@pllim, @stargaser and I discussed this and we agreed that's a good idea when coupled with #60. I'll do a tentative re-work of the schedule on that basis (i.e. step 1 of #65)
