### ISSUE TITLE
Send attendees Python Intro materials

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-workshop#60]
Consider sending attendees ASAP Python Intro materials ("Pre-req") document and Install instructions.  

Take a look at this document recommend by @bmorris3 when the oreilly power comes back on. 

> One recommendation that might work for now is to share the link to Jake VanderPlas’ free ebook A Whirlwind Tour of Python as a “prerequisite knowledge” resource: https://www.oreilly.com/programming/free/files/a-whirlwind-tour-of-python.pdf

**Comment by eblur** [comment]
There is also this, if people need more interactive learning tools:
https://www.codecademy.com/learn/learn-python-3

**Comment by eteq** [comment]
@stargaser, @pllim, and I discussed this, and we agree this is a good idea as a way to address the concern in #60.  @stargaser is taking point on this, and I propose the tentative plan be to send the following resources to the participants:

* Our existing "intro to Python" notebooks
* the two links @kelle  and @eblur suggested above
* The official python getting started page (https://www.python.org/about/gettingstarted/).

**Comment by eteq** [comment]
@pllim, @stargaser, and I agreed we should send this out soon (like within the next week) despite the fact that the workshop environment probably won't be ready for several weeks.  This maylead to more trouble at the start of the workshop due to install but we decided that's probably better than delaying sending out intro Python material.

**Comment by eteq** [comment]
Also, @stargaser will put the final email in this repo once it's finished

**Comment by stargaser** [comment]
Drafting the email at https://docs.google.com/document/d/1oo8W80ZfzJTFbRj60rM3e0fVUfT__K0qx2jwz3XMDvk/edit?usp=sharing

**Comment by pllim** [comment]
Thanks, @stargaser ! @eteq already incorporate my comment into his review there during the tag-up today. Perhaps the author order by last name alphabetically is not entirely fair, but I'll leave the ordering to you; I wouldn't mind if you move me to the back or something.

**Comment by stargaser** [comment]
The final email:

Dear Astropy Workshop Participant,

Thank you for registering for the workshop _Using Python and Astropy for Astronomical Data Analysis_, January 4, 2020, at the 235th AAS meeting in Honolulu. The team of instructors is looking forward to seeing you at the workshop!

We are not covering the basics of Python in the workshop. We list some introductory resources below, and we are sending these to you now if you feel you need to work through one or two of them before the workshop.

- https://swcarpentry.github.io/python-novice-inflammation/ 
- https://www.oreilly.com/programming/free/files/a-whirlwind-tour-of-python.pdf
- https://www.codecademy.com/learn/learn-python-3
- https://github.com/astropy/past-astropy-workshops/tree/master/aas_233_workshop/02-PythonIntro introductory notebooks from the last AAS workshop.

You can install Anaconda (https://docs.anaconda.com/anaconda/install/) for working through the examples above, or the smaller Miniconda (https://docs.conda.io/en/latest/miniconda.html) if you know what you’re doing.

The final installation instructions for the workshop will be sent around December 15th.

https://github.com/astropy/astropy-workshop#problems-or-questions is the entry point for submitting questions or issues pertaining to the workshop.

Regards, the workshop organizers,
David Shupe, Pey Lian Lim, Erik Tollerud

**Comment by stargaser** [comment]
> Also, @stargaser will put the final email in this repo once it's finished

Oops, I read this as "paste into this issue"...

**Comment by pllim** [comment]
I took the liberty to copy-paste your email to the repo at https://github.com/astropy/astropy-workshop/blob/master/00-Install_and_Setup/00_INTRO_EMAIL.md via 24f0bed8741156c8ee3203db5c09cba61fb8a53c . Thanks, @stargaser !
