### ISSUE TITLE
Do we need more Trainer T-shirts

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-workshop#61]
Let's figure out if we need more t-shirts for Honolulu by Nov 27.

Sizes:
Straight Cut:
https://www.customink.com/items/sizing/04600_lineup/standard.htm
Fitted Cut:
https://www.customink.com/items/sizing/116800_lineup/standard.htm

**Comment by stargaser** [comment]
I've emailed @kelle with the sizes needed.

**Comment by pllim** [comment]
@kelle confirmed on Slack that they are ordered. Thanks, everyone!
