### ISSUE TITLE
Make a pre-workshop survey by 2019-12-15

### ISSUE THREAD

**Issue by eblur** [astropy/astropy-workshop#62]
In past Astropy workshop surveys, people were asked to describe their comfort levels and use of Python and Astropy affiliated packages before the workshop vs after. But all responses seemed geared towards their attitudes *after* the workshop.

We need separate pre- and post-workshop surveys so we can better assess the effects of the workshop.

**Comment by stargaser** [comment]
Pinging @eblur about this, but meanwhile here are some items @kelle noted at today's tutorial telecon:

- Do we want to use the post-workshop survey we used before, or the questions from @bmorris3 or a hybrid?
- In redesigning the survey, we want to be careful to preserve previous survey questions that we may want to track over time.

In case it is useful to bundle emails to participants, the plan is to send the workshop installation instructions around December 15th.

**Comment by stargaser** [comment]
@eblur and I have corresponded by email, to set up the survey by the week of the coordination meeting.

**Comment by bmorris3** [comment]
Happy to chat about pre-workshop surveys if you like over Slack or here. :+1:

**Comment by stargaser** [comment]
@eblur has shared the forms for pre-workshop and post-workshop surveys with @pllim and  me.

**Comment by pllim** [comment]
I added some stuff to it. Feel free to edit it more.
