### ISSUE TITLE
Create issue template for workshop attendees

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-workshop#63]
@pllim is going to set up an issue template for workshop attendees to ask for help before the workshop.  This template should use github's fancy machinery to auto-add a label (which @pllim found via google but I can't find now...).

This would use the `question` label, so then helpers can filter on that label to watch for questions (or "not that label" for non-question issues)

**Comment by pllim** [comment]
Done. I did this directly in repo settings, so it pushed straight to `master`. I apologize for any inconvenience caused. You can see an example usage at #67, where the label is automatically added upon issue creation.
