### ISSUE TITLE
Create installation thumb drives?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-workshop#64]
For offline installation of `conda`, packages, and materials we need for the workshop. Need to cover all three major OSes if possible -- OSX, Windows, Linux.

**Comment by bsipocz** [comment]
Is creating a "homework" prior the workshop feasible? E.g. a script that only works if everything is installed? Folks need to send back a result number for said script, so you can track how many has a working environment?

**Comment by kelle** [comment]
I think this is a great idea! Just a matter of someone making time to put
it together. Maybe make a script that does all the imports and does a
couple trivial things and reveals a fun Easter egg of some sort.
-- 
kelle (via iOS)

**Comment by bsipocz** [comment]
We certainly was planning to do this for the astroML workshop, but for that one we already stated to have numerical python experience, so we can assume working scipy/scikit-learn/etc installs already.

I suppose I can help out here with the script, too if someone else takes care of setup instructions.

**Comment by pllim** [comment]
A script like this that @sosey created? https://github.com/spacetelescope/aas229_workshop/blob/master/check_env.py

**Comment by bsipocz** [comment]
💯

 job done it seems :)

**Comment by pllim** [comment]
Well, someone still need to move it over. Do you wanna do it, @bsipocz ?

**Comment by pllim** [comment]
During the coordination meeting, it was decided that this is more work than its worth. We will have other alternatives (e.g., binder, rendered HTML)
