### ISSUE TITLE
Update schedule for AAS235 

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-workshop#65]
- [x] Update schedule with known immediate actions (esp #59)
- [x] Ask teachers (when that list exists, which @stargaser is working on) to do their lessons, and report back how long it takes (deadline is 2019-12-06, #90 )
- [x] Update schedule based on that feedback

**Comment by pllim** [comment]
Don't forget #56

**Comment by eteq** [comment]
Hard-to-interpret notes from planning telecon just now (I will updated schedule later with this):

* -15 min from contributing
* +15 to coordinates

+15 to WCS/Images to add in
* load an image as a `CCDData`
* do arithmetic on that (flat fiedling?)
* point people to ccdproc
-15 from specutils or *maybe* photutils

* add modeling (a bit) to specutils

if we add time series to table +15 there and, -15 from specutils or photutils

**Comment by pllim** [comment]
Fixed by #125. If the schedule needs further changes, it can be done on a case-by-case basis, so there is no need to keep this open.
