### ISSUE TITLE
Do we need to keep non-master branches?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-workshop#68]
There are two branches named `brett-update` and `brett-update-2`; do we need to keep them here?

**Comment by bsipocz** [comment]
No, I think we need to follow the astropy contributing guidelines and thus folk need to open branches on their forks rather than in the main repo as no need to propagate those branches for everyone cloning the repo.

**Comment by bsipocz** [comment]
I don't have write access, but one of those branches has been merged into master, so clearly can be deleted, and the other one is also obsolete with a closed PR associated with it.

**Comment by bmorris3** [comment]
I don't think I have write access either, but both branches can be deleted by someone who has permissions :+1:.

**Comment by bsipocz** [comment]
weird, you must have had access to create them. 🤷‍♀

**Comment by bmorris3** [comment]
You're right @bsipocz, I just wasn't looking at them correctly. I've deleted them!

**Comment by pllim** [comment]
Thanks!
