### ISSUE TITLE
Try to get two more helpers for 2020 AAS workshop

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-workshop#71]
Right now we have 7 instructors for 90 participants slots.  To get 1:10 ratio we should call for two more helpers. Will send out a message to astropy-dev and then try via other channels if that doesn't work (or do nothing... 7 helpers for 90 participants is doable, if not ideal).

**Comment by kelle** [comment]
Who are the 7?

**Comment by pllim** [comment]
@kelle, please see #73

**Comment by stargaser** [comment]
Email sent to astropy-dev list on 2019 Nov 26. No email responses received, but @larrybradley signed up to help which puts us at eight total. Currently we have 79 registrants with a cap of 90.

Eight is Enough?

**Comment by pllim** [comment]
@eteq will ask on Slack for more. But if no one else volunteers, it is not a deal breaker.

**Comment by stargaser** [comment]
@tomdonaldson replied to the Slack message that he can help. Hurray!
