### ISSUE TITLE
Update environment for 2020 

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-workshop#72]
For the AAS 2020 workshop, @pllim is proposing we switch to "mostly pip" as the source of packages.  That is, conda only for things where it's really necessary/useful (scipy, matplotlib, nodejs, numpy), and stick with pip for the python-only packages.

Also need to update to python 3.7, and use astropy 4.0 (rc for now, release by the time of workshop, hopefully).

@pllim says she'll do this in the next week.

**Comment by bsipocz** [comment]
scipy/numpy/matplotlib also have wheels 🤷‍♀

**Comment by bmorris3** [comment]
I don't object to this, but I will note that we've had probably 200 people follow the existing instructions and have had a success rate approaching 100% – I'd be cautious about changing something so successful!

**Comment by pllim** [comment]
They won't be successful no more if astropy 4.0 is not on conda channel before the workshop.

**Comment by bsipocz** [comment]
I would say don't build anything on 4.0 and that would require brand new everything. Even going through the full RC testing and releasing by the workshop is questionable (we aim to get there, but anything can happen, and I would rather not rush an LTS for the sake of a workshop).

But then every piece of the stack should work with astropy 4.0, which is problematic and requires a whole bunch of new releases. Is that even realistic to assume, while the material covers only stuff that's in 3.2?

**Comment by pllim** [comment]
But there is much good stuff in 4.0, like modeling refactor, new WCS function, etc.

Also the caching behavior has changed.

**Comment by bsipocz** [comment]
Yes, that's right. But is any of those affect the material we are suppose to teach or just opening up new cans of worms? 
E.g. we cannot teach specutils atm if we require 4.0. In fact I'm not sure how many of the actually released versions of affiliated/coordinated packages are compatible (as we test their master branches rather than the released ones). And it's an extra cat hurdling challenge to make sure we get the releases out for all those packages as well as the LTS.

**Comment by bsipocz** [comment]
(I for one would love to have 4.0 for the Table to showcase TimeSeries awesomeness, but nevertheless feel it a bit risky to rely on 4.0 for everything)

**Comment by pllim** [comment]
In that case, I defer to @stargaser , @eteq , @kelle , and @eblur . If you want to use 3.x, I will edit the version of `astropy` in #74 accordingly but the rest of the change should not be affected, unless you really want to keep the status quo here.

**Comment by kelle** [comment]
I think this is an important issue and I do not know enough to have a strong opinion. I abstain.

**Comment by stargaser** [comment]
My vote is for the 4.0 release candidate. Presenters will be checking their notebooks so we can revisit if there are problems.

**Comment by bsipocz** [comment]
The issue with the release candidate that it won't be available via conda, but pip only. As well as I mentioned some packages are not compatible with it, and without insurances that there'll be new releases before the workshop it would be a bit embarrassing for said packages.
Sure, we could have separate environment for the notebooks, but given the workshop is aimed to be suitable for novice users, I would not go into that deep into the weeds.

**Comment by eteq** [comment]
@stargaser, @pllim and I discussed this out-of-band, and here's what we're thinking:

1. We merge #74 mostly as-is (it implemented the original suggestion here), which includes Astropy 4.0rc1 and broadly speaking a conda->pip shift.
2. The instructors will each *try* their notebooks using that environment.
3. If the instructors all report back lots of issues, we will back out to using 3.2.x and/or conda-mostly.  We'll make the go-no go decision on this during the coordination meeting (I'll make a new issue for that), but with the full understanding that "full revert" is a completely valid option given @bsipocz's very reasonable concern here about not having this rush an LTS.
4. The times series or not decision can be deferred until we've done the above.
