### ISSUE TITLE
Send email to instructors with very clear testing instructions and deadline of 2019-12-06

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-workshop#79]
This is an ASAP to-do, particularly given #72 and the need to get install instructions out by mid-Dec.  Gist is that we need to send an email to the instructors asking them to do their sections and report back:

* How long it takes them to do it (bearing in mind that an instructor will probably go 2x to 3x faster than a student)
* Affirming that they followed the install instructions, and report if it worked correctly with 4.0rc1.

The deadline to ask the instructors to do this is Dec 6 so that there's time to fold that into the #72 discussion.

**Comment by eteq** [comment]
@pllim asked (in-person) that I add: "If we don't hear back by the deadline, @pllim will use Mommy voice on you".

**Comment by pllim** [comment]
That's right, children!

**Comment by stargaser** [comment]
I've sent the email to the presenters.

**Comment by pllim** [comment]
Thanks. But #74 is not merged yet. Let's continue the conversation in that email.
