### ISSUE TITLE
Quantity section improvements

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-workshop#8]
Two existing notebooks need to be combined.
Units and Quantity need to be introduced with a motivating example.

**Comment by kelle** [comment]
discuss where Quantities don't work and why. E.g., matplotlib, numpy.histogram.

**Comment by bmorris3** [comment]
@kelle/@eteq – I'm looking at combining the notebooks now. It looks like the major difference is that the notebook `Tutorial_from_Astropy_Quantity` has a really long example on molecular clouds. Should I transfer that exercise to the newer notebook (`Astropy_Units`) and put it under the `Putting it all together` subsection?
