### ISSUE TITLE
Decide if we're doing 4.0 or 3.2.x (and rollback pllim PR if needed) by 2019-12-11

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-workshop#80]
This is the follow-on to #74 if we follow the plan in https://github.com/astropy/astropy-workshop/issues/72#issuecomment-558803069 - by Dec 11 we should have a decision on the install instructions to either:

1.  Use Astropy 4.0/4.0rc
2. Use Astropy 3.2.x

as well as either one of these:

1. Use the "mostly-pip" environment
2. Use a "mostly-conda" environment

**Comment by pllim** [comment]
Decision made: We will stick with astropy 4.0
