### ISSUE TITLE
Revise "Other list" in schedule

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-workshop#81]
I suppose it wouldn't hurt to review the list under:

``Other tools we can answer questions about but probably won't discuss explicitly``

Currently there are 5 (6) packages listed there, and I suspect the subset of us not from ST cannot really answer questions about them.

**Comment by pllim** [comment]
I can probably reroute them if no one can answer the ST ones. @larrybradley and @eteq should be able to help in that regard too. But it is indeed good to revisit the list.

**Comment by eteq** [comment]
Good point, @bsipocz , but looking more closely at this list, it seems almost all of the mentioned things are *already* affiliated packages, so I guess it's not even necessary to list them. Probably we should just delete everything except the git part, and perhaps add in `jupyter` and perhaps `numpy`/`scipy`?

**Comment by bsipocz** [comment]
@eteq - I still see value in giving a list where where are e.g. maintainers, so for sure can answer questions. 

Alternatively pointing to the schedule of the booth is probably even better?

**Comment by bsipocz** [comment]
Also, I wonder whether it would make any sense to collect other events, posters, talks that are somewhat related, or we wouldn't have many of those anyway?

E.g. some of the other workshops are covering some affiliated packages (but reg is finished, so probably doesn't matter). But then there can be talks and posters 🤷‍♀ It doesn't necessarily connecting to the workshop, but coordinating and promoting our conference participation.

**Comment by pllim** [comment]
👍 to advertise the booth schedule.
