### ISSUE TITLE
astroquery error in coordinates notebook

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-workshop#83]
In `In[15]`, from running this:
```python
from astroquery.sdss import SDSS
sdss = SDSS.query_region(coordinates=hcg7_center, radius=20*u.arcmin, 
                         spectro=True, 
                         photoobj_fields=['ra','dec','u','g','r','i','z'])
```

I get:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-15-7c3b8bbd638e> in <module>
----> 1 from astroquery.sdss import SDSS
      2 sdss = SDSS.query_region(coordinates=hcg7_center, radius=20*u.arcmin, 
      3                          spectro=True,
      4                          photoobj_fields=['ra','dec','u','g','r','i','z'])

~/anaconda/envs/astropy-workshop/lib/python3.7/site-packages/astroquery/sdss/__init__.py in <module>
     25 conf = Conf()
     26 
---> 27 from .core import SDSS, SDSSClass

~/anaconda/envs/astropy-workshop/lib/python3.7/site-packages/astroquery/sdss/core.py in <module>
     17 from ..utils import commons, async_to_sync, prepend_docstr_nosections
     18 from ..exceptions import RemoteServiceError, NoResultsWarning
---> 19 from .field_names import (photoobj_defs, specobj_defs,
     20                           crossid_defs, get_field_info)
     21 

~/anaconda/envs/astropy-workshop/lib/python3.7/site-packages/astroquery/sdss/field_names.py in <module>
     11 
     12 from . import conf
---> 13 from ..utils.testing_tools import MockResponse
     14 
     15 __all__ = ['get_field_info', 'photoobj_defs', 'specobj_defs', 'crossid_defs']

~/anaconda/envs/astropy-workshop/lib/python3.7/site-packages/astroquery/utils/testing_tools.py in <module>
      4 import json
      5 
----> 6 import pytest
      7 
      8 # save original socket method for restoration

ModuleNotFoundError: No module named 'pytest'

```

**Comment by bsipocz** [comment]
@adrn - hmm, interesting, it's a legitime issue in astroquery, I would suggest to move this issue to there (and ultimately warm up https://github.com/astropy/astropy/pull/7952 and apply it to all coordinated packages).

**Comment by bsipocz** [comment]
Never mind, I've opened a separate issue rather than moving this one: https://github.com/astropy/astroquery/issues/1591

I would suggest the easy workaround for the workshop, to simply require pytest being installed. Otherwise we need to require a much newer astroquery version (as I'm sure it will be fixed by the time of the workshop).

**Comment by bsipocz** [comment]
https://github.com/astropy/astroquery/pull/1570 is the one that brought in the regression, so conda installed 0.3.9 version should work. There was only 2 dev releases since, so the situation is not that bad as I first thought.

**Comment by pllim** [comment]
`astroquery` 0.3.9 does not work with `astropy` 4.0 -- tried an failed at #91

**Comment by bsipocz** [comment]
yes, please ignore  me. it meant to be 0.3.10, not 0.3.9...

**Comment by pllim** [comment]
Oh... So... Do you think astropy/astroquery#1593 is sufficient or I need to revive #91 ?

**Comment by bsipocz** [comment]
the fix in astroquery is sufficient, but I fixing up astropy/astroquery#1592 is a blocker, so I can't just merge it yet.

**Comment by bsipocz** [comment]
anyway,  it'll be done next week, the latest.

**Comment by pllim** [comment]
Okay, let's handle this over at `astroquery` then.

**Comment by adrn** [comment]
As a quick fix, we should just add pytest to the workshop environment file.

**Comment by pllim** [comment]
@adrn , it is added in 855ccaf3084bff8c340e4882895793f357945bca . If this works for you, please close the issue. Thanks!

**Comment by adrn** [comment]
I remade my environment and tried the coordinates notebook - looks good now!
