### ISSUE TITLE
Do not duplicate instructor info in multiple READMEs

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-workshop#96]
Instructor assignments are in the root-level README, but then I also see instructor names listed in individual chapter READMEs. This only increases maintenance burden for future workshops and the risk of all the READMEs have conflicting information.

I propose that instructors to be only listed in root-level README.

**Comment by stargaser** [comment]
This is an excellent suggestion, to list the instructor names only in the top-level README. We can just update "Author" in the chapter READMEs as presenters update the content.
